Longtext input has x on top of scrollbar
informatics-isi-edu/chaise pull request #2328
Opened 2023-07-06 03:16 UTC by PoornimaVKrishnan

This PR is related to 
https://github.com/informatics-isi-edu/chaise/issues/2318

It focuses on adding a padding when there is a scrollbar in the textarea which avoids overlapping between the text, cross button and scrollbar

2023-07-06 20:46 UTC, RFSH requested changes
Your changes looks good overall. I asked for some small changes. By the way, In the issue I forgot to mention json-field.tsx. So make sure to apply a similar change to the `textarea` in there as well.

2023-07-06 20:46 UTC, RFSH commented on src/utils/input-utils.ts
> +export const hasScrollbar = (element: any) => {
Change this to `hasVerticalScrollbar`

2023-07-06 20:46 UTC, RFSH commented on src/assets/scss/_input-switch.scss
> +    padding-right: 2rem !important;
Add a comment above this rule saying that you're adding this rule to increase the space to accommodate for scrollbar

2023-07-06 20:46 UTC, RFSH commented on src/assets/scss/_input-switch.scss
> +    margin-right: 10px;
Add a similar comment for this as well

2023-07-07 17:46 UTC, PoornimaVKrishnan commented
@RFSH 
Addressed all comments

2023-07-07 22:43 UTC, RFSH approved these changes

2023-07-07 22:43 UTC, merged